Explain /-in-calc not deprecated.
sass/sass-site pull request #595
Opened 2021-11-24 22:38 UTC by Awjin

2021-11-24 23:30 UTC, nex3 requested changes

2021-11-24 23:30 UTC, nex3 commented on source/documentation/breaking-changes/slash-div.html.md.erb
> +Alternatively, users can wrap division operations inside a `calc()` expression.
I'd explicitly mention that Sass will simplify it and return a single number.

2021-11-26 18:27 UTC, stof commented
Refs sass/dart-sass#1559

2021-12-03 08:33 UTC, stof approved these changes

2021-12-03 21:58 UTC, nex3 approved these changes

2021-12-03 21:59 UTC, merged