Make compatibility callout toggle a button
sass/sass-site pull request #625
Opened 2022-05-03 17:42 UTC by jathak

Fixes #598.

2022-05-03 17:44 UTC, jathak commented
@nex3: Can you deploy this branch so we can confirm it works? I'm having trouble getting the site to build locally.

2022-05-10 21:52 UTC, nex3 commented
It looks like this substantially changes the look of the button, and also breaks the on-click behavior. You may need to load the site locally to debug this—let me know if I can help you debug any issues that come up.

![image](https://user-images.githubusercontent.com/188/167727911-34d79dc3-fc97-46fe-abd4-af9c17ad055a.png)

2022-07-18 20:48 UTC, nex3 requested changes
Can you add a comment explaining what the href is doing?

2022-08-02 22:54 UTC, nex3 approved these changes

2022-08-22 20:19 UTC, merged