Document the moz-document breaking change on the sass website.
sass/sass-site pull request #667
Opened 2022-09-03 00:57 UTC by stof

Currently, the link in the deprecation warning goes to a website that does not even exist anymore, relying on the web-archive. And this website does not give any details about the *Sass* breaking change.

This references this breaking change on the website like the others (still linking to the Firefox deprecation announcement on web-archive as part of the explanation).

2022-09-06 23:51 UTC, Goodwine requested changes
Can you also add an entry in `data/documentation.yml`?

2022-09-06 23:51 UTC, Goodwine commented on source/documentation/breaking-changes/moz-document.md.erb
> +As [Firefox dropped support for them], Sass will also drop support.
Per this comment - https://github.com/sass/dart-sass/issues/378#issuecomment-1238704220
Sass won't drop support entirely, only for the special parsing in favor of interpolation within unknown at-rules

2022-09-07 07:44 UTC, stof commented
@Goodwine updated

2022-09-07 17:48 UTC, Goodwine approved these changes

2022-09-07 17:48 UTC, Goodwine commented on source/documentation/breaking-changes/moz-document.md.erb
> +  Firefox used to have a @-moz-document rule requiring a special parsing. As
```suggestion
  Firefox used to have a @-moz-document rule requiring special parsing. As
```

2022-09-07 17:48 UTC, Goodwine commented on source/documentation/breaking-changes/moz-document.md.erb
> +parsing.
```suggestion
As [Firefox dropped support for them], Sass will also drop support for the special
parsing and will treat it as an unknown at-rule.
```

2022-09-07 17:55 UTC, merged